gtimelog.appdata.xml
AppData files are suggested when packaging desktop applications for Fedora, so here is a (very basic) one. It would be great to have translations and an extended description, but at least it's a start.
=> Add AppData file

setup.py, src/gtimelog/tests/test_main.py, src/gtimelog/tests/test_timelog.py
There's no need to pull in an extra dependency for Python 3.   We run gtimelog in Python 3 on Debian.
=> Use unittest.mock in Python 3.

NEWS.rst, po/en.po, po/gtimelog.pot, po/lt.po, src/gtimelog/gtimelog.ui, src/gtimelog/main.py, src/gtimelog/menus.ui
Press Ctrl+F to open it (or click the new View menu entry).  Type some text.  Only those tasks matching the text will be shown in the task log, along with the total time taken by those tasks.
This performs a simple substring filtering.  It is sufficient for me right now.
You can cancel the filtering by pressing Esc or Ctrl+F again.
Incidentally, this also fixes #86.
=> Add a search/filter bar

gtimelog
I did
```
ln -s $PWD/gtimelog ~/bin/
```
but the sources could not be found.
=> Make symlink to gtimelog in source directory work

src/gtimelog/main.py
Instead of using Gio to fetch the remote task list, use Soup directly.
If the resource is password-protected, consult the keyring, asking
the user if needed.
Based on the original implementation from Collabora’s fork written by:
* Gustavo Noronha Silva <@kov>
* Will Thompson <@wjt>
* Jonny Lamb <@jonnylamb>
`ask_the_user()` rewritten by Andrej Shadura to make use of the standard
GTK+ dialogs as implemented by `GtkMountOperation`.
=> Support HTTP authentication and Gnome Keyring

.travis.yml, CHANGES.rst, appveyor.yml, setup.py, tox.ini
See https://github.com/travis-ci/travis-ci/issues/9815 for the reason for the `sudo` and `dist: xenial` bits
=> Add Python 3.7 support

docs/index.rst
It's easy to overlook the documentation on how to back-date an entry.  I've moved this up into it's own section under the other syntax sections.  Correcting mistakes section is now focused on editing the text file.
=> Docs -- Moved back-dating into own section

src/gtimelog/debian-paths.py, src/gtimelog/main.py, src/gtimelog/paths.py
The idea here is that the Debian package will no longer need to patch
main.py but instead can replace paths.py with debian-paths.py during
package build.
Cc: @andrewshadura
=> Refactor resource location logic

src/gtimelog/main.py
I'm using GTimeLog on MS-Windows and noticed that the menu entries "Edit log" and "Edit tasks" didn't work out of the box. As it turned out the `Gtk.show_uri()` didn't work to open the text editor. So i changed `Gtk.show_uri()` to `os.startfile()`. With this workaround (but only stepping in if running on MS-Windows) the mentioned menu entries work as expected.
Maybe this is also helpful for other MS-Windows users. Please feel free to decide if you find it worth to incorporate into upstream.
=> Use os.startfile() for "Edit log" and "Edit tasks" on MS-Windows

src/gtimelog/CONTRIBUTORS.rst, src/gtimelog/tests/test_timelog.py, src/gtimelog/timelog.py
Entries with '***' should be completely ignored. Do not include them when computing the total.
Also add a simpler test case for totals that includes an entry with '***'. While the totals are already tested by the other test cases, this allows to see if there is a bug in the totals itself.
This fixes #132.
=> Exclude entries with three asterisks from totals

README.rst
The change log says that support for 3.4 was dropped.
=> Fix required Python version.

CHANGES.rst, src/gtimelog/main.py
The error was
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/gtimelog/main.py", line 979, in tasks_downloaded
content.decode('UTF-8', 'replace').replace('\n', '\n  '))
AttributeError: 'str' object has no attribute 'decode'
because apparently Soap gives us a unicode string (on Python 3) instead
of bytes?
I've tested the new code on both Python 2 and 3, on a URL that responds
with Content-Type: text/plain; charset=utf-8 and returns non-ASCII data.
Fixes #153.
=> Fix error when using remote task list

README.rst
gtimelog is also packaged for Fedora, probably worth mentioning it.
=> Add Fedora as source of gtimelog package

src/gtimelog/timelog.py
We should strip spaces from category and task. 
Spaces shouldn’t have a meaning for grouping.
=> Strip spaces from category and task

src/gtimelog/main.py, src/gtimelog/secrets.py, src/gtimelog/utils.py
This makes `main` a bit less of a mess.
I’ve also changed the constructor to make `Authenticator` tie itself into the soup session automatically.
=> Split keyring and secrets handling into a separate module

CHANGES.rst, docs/index.rst, src/gtimelog/CONTRIBUTORS.rst, src/gtimelog/tests/test_timelog.py, src/gtimelog/timelog.py
Adds ability to add a positive time offset which is relative to the last created entry.
e.g.  `+30 meeting` will add a meeting entry 30 minutes after the last entry, provided the entry would not be in the future.
closes #209
=> 209 positive time offset entry

CHANGES.rst, src/gtimelog/main.py
It is now only required to enter characters of the entry in the correct order to find an entry.
Using the entries in the screenshot in the README.
'tr' would suggest the entry 'gtimelog: experimental rewrite (GH #31)' because the 't' on index 1 is followed by an 'r' later in the entry text.
=> Change entry search to be fuzzy.

src/gtimelog/tests/test_timelog.py, src/gtimelog/timelog.py
The tasks themselve were anyway not sorted, so better be consistent. Makes also sure that the "Other" group is always at the end. Closes #182
=> Keep config file order in tasks pane

other-requirements.txt, src/gtimelog/main.py, src/gtimelog/secrets.py
Using https://libsoup.org/libsoup-3.0/migrating-from-libsoup-2.html as a guide, I rewrote existing code base to Soup 3.0.
Test results:
```
% ./runtests
.........................................................................................................
----------------------------------------------------------------------
Ran 105 tests in 0.317s
OK
```
I also did manual testing with
```
gsettings set org.gtimelog remote-task-list true
gsettings set org.gtimelog task-list-url https://gist.github.com/mgedmin/4609f92e2c11502386f5/raw
```
As well as with an invalid URL.
=> Move from Soup 2.4 to Soup 3.0.

src/gtimelog/secrets.py
#238 was incomplete, as it didn't update secrets.py accordingly to the new Soup library version 3.0.
Now, I set
```
gsettings set org.gtimelog task-list-url http://httpbin.org/basic-auth/q/p
```
The user is q and the password is p.
Tested thus, always deleting the ~/.local/share/gtimelog/remote-tasks.txt in between:
*Cancelled authentication.
*Correct user/password, without saving in the keyring.
*Correct user/password, with saving in the keyring, deleting cache file and restarting gtimelog.
*Wrong user/password.
I couldn't contrast this with the existing behavior in 0.11.3-2 because there I get [this error](https://github.com/gtimelog/gtimelog/files/12585244/0.11.3-2.txt) (should I open an issue about it)?
=> Fix incomplete move to Soup 3.0 for authenticator (secrets.py).

gtimelog.appdata.xml
- Update to the newer standard (#241)
- Set proper app id
- Add launchable
=> Validate appdata

src/gtimelog/gtimelog.css, src/gtimelog/gtimelog.ui, src/gtimelog/main.py
override_font is deprecated (since Gtk 3.16).
Fixes:
```
/home/juergen/ghq/github.com/gtimelog/gtimelog/src/gtimelog/main.py:1791: DeprecationWarning: Gtk.Widget.override_font is deprecated
self.override_font(Pango.FontDescription.from_string("Monospace"))
```
=> Use CSS Provider to set font-family
